---
- hosts: all
  become: true
  tasks:

   - name: install apache2 package
     apt: 
       name: 
         - "{{ apache_packages }}"
         - "{{ php_package }}"
       state: latest
       update_cache: yes
